FROM openjdk:17
ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} application.jar

ARG ACCESS_EXP
ENV ACCESS_EXP ${ACCESS_EXP}

ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}

ARG DB_URL
ENV DB_URL ${DB_URL}

ARG DB_USER
ENV DB_USER ${DB_USER}

ARG JWT_SECRET
ENV JWT_SECRET ${JWT_SECRET}

ARG REFRESH_EXP
ENV REFRESH_EXP ${REFRESH_EXP}

ARG MAIL_USER
ENV MAIL_USER ${MAIL_USER}

ARG MAIL_PASSWORD
ENV MAIL_PASSWORD ${MAIL_PASSWORD}

ARG BUCKET
ENV BUCKET ${BUCKET}

ARG DIRECTORY
ENV DIRECTORY ${DIRECTORY}

ARG ACCESS_KEY
ENV ACCESS_KEY ${ACCESS_KEY}

ARG SECRET_KEY
ENV SECRET_KEY ${SECRET_KEY}

ARG VAULT_URL
ENV VAULT_URL ${VAULT_URL}

ARG VAULT_TOKEN
ENV VAULT_TOKEN ${VAULT_TOKEN}

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "application.jar"]