spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  redis:
    host: ${REDIS_HOST:redis.xquare.app}
    port: ${REDIS_PORT:6379}
  jackson:
    property-naming-strategy: SNAKE_CASE
    properties:
      hibernate:
        show_sql: true
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            timeout: 5000
jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${ACCESS_EXP}
  refresh-exp: ${REFRESH_EXP}
server:
  servlet:
    context-path: /merge
logging:
  level:
    root: info
cloud:
  aws:
    s3:
      bucket: ${BUCKET}
      dir: ${DIRECTORY}
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
      region: ap-northeast-2
